language: python
python:
  - "3.4"
services: mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database zip_address default charset=utf8;'
  - unzip data/sql_zenkoku.zip -d data
  - mysql zip_address < data/zenkoku.sql
script:
  - python manage.py test
after_script:
  - rm data/zenkoku.sql
